const express=require('express'),path=require('path');const{Pool}=require('pg');
const app=express();app.use(express.json({limit:'3mb'}));app.use(express.static(__dirname));
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
const kinds=new Set(['players','schedule','sessions','observations','feedback','idp','matchreviews','reflections']);
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS coach_records(id BIGSERIAL PRIMARY KEY,kind TEXT NOT NULL,record_id TEXT UNIQUE NOT NULL,record_date DATE,payload JSONB NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW())`);await pool.query(`CREATE INDEX IF NOT EXISTS idx_records_kind_date ON coach_records(kind,record_date DESC)`)}
const rid=k=>k.slice(0,3)+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,7);
app.get('/api/health',async(q,s)=>{try{await pool.query('select 1');s.json({ok:true})}catch(e){s.status(500).json({ok:false,error:e.message})}});
app.get('/api/data',async(q,s)=>{try{let r=await pool.query('SELECT * FROM coach_records ORDER BY record_date DESC NULLS LAST,created_at DESC'),o={};[...kinds].forEach(k=>o[k]=[]);r.rows.forEach(x=>o[x.kind].push({id:x.record_id,date:x.record_date?String(x.record_date).slice(0,10):undefined,...x.payload}));s.json(o)}catch(e){s.status(500).json({error:e.message})}});
app.post('/api/:kind',async(q,s)=>{let k=q.params.kind;if(!kinds.has(k))return s.status(404).end();try{let id=rid(k),d=q.body.date||q.body.reviewDate||null;await pool.query('INSERT INTO coach_records(kind,record_id,record_date,payload) VALUES($1,$2,$3,$4)',[k,id,d,q.body]);s.json({id,...q.body})}catch(e){s.status(500).json({error:e.message})}});
app.get('/api/export',async(q,s)=>{let r=await pool.query('SELECT * FROM coach_records ORDER BY created_at');s.setHeader('Content-Disposition','attachment; filename="coach-os-backup.json"');s.json({exportedAt:new Date().toISOString(),records:r.rows})});
app.get('/api/report/weekly',async(q,s)=>{let r=await pool.query(`SELECT * FROM coach_records WHERE record_date>=CURRENT_DATE-INTERVAL '6 days' ORDER BY record_date`),rows=r.rows,by=k=>rows.filter(x=>x.kind===k).map(x=>({date:String(x.record_date).slice(0,10),...x.payload})),ss=by('sessions'),oo=by('observations'),ff=by('feedback'),rr=by('reflections');s.json({start:new Date(Date.now()-6*864e5).toISOString().slice(0,10),end:new Date().toISOString().slice(0,10),totals:{sessions:ss.length,observations:oo.length,feedback:ff.length,reflections:rr.length},themes:[...new Set(ss.map(x=>x.theme).filter(Boolean))],followups:oo.filter(x=>x.followUp).map(x=>({player:x.player,action:x.followUp}))})});
app.get('*',(q,s)=>s.sendFile(path.join(__dirname,'index.html')));
init().then(()=>app.listen(process.env.PORT||3000)).catch(e=>{console.error(e);process.exit(1)});